#You will have to replace some of the values with the the locations that are relevant
#for your machine
#Submit a job using this script by running the following from the npx node
#condor_submit NPXSubmissionTemplate.sub

Executable = REPLACE_ME/ExampleSubmission.sh
Error = REPLACE_ME/log-files/MyErrorOutput_$(Process).err
Output = REPLACE_ME/log-files/MyStandardOutput_$(Process).out
Log = /scratch/YOURNAMEHERE/npxoutput_$(Process).log
request_memory = 2GB

Arguments= Test! Process

Queue 5
